sudo: required
language: generic
matrix:
  include:
    - name: "Ubuntu 18.04"
      os: linux
      env: CONTAINER=ubuntu1804
      services: docker
install:
  # Build the docker container
  - pushd $TRAVIS_BUILD_DIR
  - if [[ $CONTAINER != "osx" ]]; then docker-compose build test-$CONTAINER ; fi
script:
  - if [[ $CONTAINER != "osx" ]]; then docker-compose run test-$CONTAINER; else bash test/scripts/test_osx.sh ; fi
